name: Android Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Isse tum manually bhi build start kar sakte ho

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Ye step permissions aur missing files fix karega
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant Execute Permission
        run: chmod +x gradlew || true

      # Asli Build Command
      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon

      # APK ko download ke liye ready karna
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: EraShare-Debug-APK
          path: app/build/outputs/apk/debug/app-debug.apk
          
